<?php
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

use App\Database;
use App\Response;

require_once __DIR__ . '/../vendor/autoload.php';

try {
    $pdo = Database::connection();

    // 1. Create points_of_sale table
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS `points_of_sale` (
          `id` char(36) NOT NULL,
          `country_type` enum('egypt','international') NOT NULL DEFAULT 'egypt',
          `country_ar` varchar(100) NOT NULL DEFAULT 'مصر',
          `country_en` varchar(100) NOT NULL DEFAULT 'Egypt',
          `city_ar` varchar(100) NOT NULL,
          `city_en` varchar(100) NOT NULL,
          `name_ar` varchar(150) NOT NULL,
          `name_en` varchar(150) NOT NULL,
          `branch_name_ar` varchar(150) DEFAULT NULL,
          `branch_name_en` varchar(150) DEFAULT NULL,
          `address_ar` text NOT NULL,
          `address_en` text NOT NULL,
          `phone` varchar(60) DEFAULT NULL,
          `whatsapp` varchar(60) DEFAULT NULL,
          `google_maps_url` text DEFAULT NULL,
          `is_main_distributor` tinyint(1) NOT NULL DEFAULT 0,
          `is_active` tinyint(1) NOT NULL DEFAULT 1,
          `display_order` int(11) NOT NULL DEFAULT 0,
          `created_at` datetime NOT NULL DEFAULT current_timestamp(),
          `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
          PRIMARY KEY (`id`),
          KEY `country_type` (`country_type`),
          KEY `city_ar` (`city_ar`),
          KEY `is_active` (`is_active`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    ");

    // Clear old sample branches to populate fresh set
    $pdo->exec("TRUNCATE TABLE `points_of_sale`");

    $branches = [
        // --- داخل مصر (Egypt) ---
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'القاهرة',
            'city_en' => 'Cairo',
            'name_ar' => 'مكتبة مدبولي',
            'name_en' => 'Madbouly Bookshop',
            'branch_name_ar' => 'فرع وسط البلد',
            'branch_name_en' => 'Downtown Branch',
            'address_ar' => '6 ميدان طلعت حرب، وسط البلد، القاهرة',
            'address_en' => '6 Talaat Harb Square, Downtown, Cairo',
            'phone' => '02-23919888',
            'whatsapp' => '+201026600868',
            'google_maps_url' => 'https://maps.google.com/?q=Madbouly+Bookshop+Talaat+Harb+Cairo',
            'is_main_distributor' => 1,
            'display_order' => 1,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'القاهرة',
            'city_en' => 'Cairo',
            'name_ar' => 'مكتبة تنمية',
            'name_en' => 'Tanmia Bookstore',
            'branch_name_ar' => 'فرع هدى شعراوي',
            'branch_name_en' => 'Hoda Shaarawy Branch',
            'address_ar' => '19 شارع هدى شعراوي، باب اللوق، وسط البلد، القاهرة',
            'address_en' => '19 Hoda Shaarawy St, Bab Al-Louq, Downtown, Cairo',
            'phone' => '01026600868',
            'whatsapp' => '+201026600868',
            'google_maps_url' => 'https://maps.google.com/?q=Tanmia+Bookstore+Cairo',
            'is_main_distributor' => 1,
            'display_order' => 2,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'القاهرة',
            'city_en' => 'Cairo',
            'name_ar' => 'مكتبات ديوان',
            'name_en' => 'Diwan Bookstore',
            'branch_name_ar' => 'فرع الزمالك',
            'branch_name_en' => 'Zamalek Branch',
            'address_ar' => '159 شارع 26 يوليو، الزمالك، القاهرة',
            'address_en' => '159 26th of July St, Zamalek, Cairo',
            'phone' => '02-27362598',
            'whatsapp' => '+201222407084',
            'google_maps_url' => 'https://maps.google.com/?q=Diwan+Bookstore+Zamalek+Cairo',
            'is_main_distributor' => 0,
            'display_order' => 3,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'القاهرة',
            'city_en' => 'Cairo',
            'name_ar' => 'مكتبات الشروق',
            'name_en' => 'Shorouk Bookshop',
            'branch_name_ar' => 'فرع سيتي ستارز',
            'branch_name_en' => 'Citystars Branch',
            'address_ar' => 'سيتي ستارز مول، المرحلة الأولى، الدور الثالث، مدينة نصر، القاهرة',
            'address_en' => 'Citystars Mall, Phase 1, 3rd Floor, Nasr City, Cairo',
            'phone' => '02-24800450',
            'whatsapp' => '+201000600700',
            'google_maps_url' => 'https://maps.google.com/?q=Shorouk+Bookshop+Citystars+Cairo',
            'is_main_distributor' => 0,
            'display_order' => 4,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'القاهرة',
            'city_en' => 'Cairo',
            'name_ar' => 'مكتبة أ Alef',
            'name_en' => 'Alef Bookstore',
            'branch_name_ar' => 'فرع التجمع الخامس',
            'branch_name_en' => 'Fifth Settlement Branch',
            'address_ar' => 'داون تاون مول، شارع التسعين، التجمع الخامس، القاهرة الجديدة',
            'address_en' => 'Downtown Mall, 90th Street, 5th Settlement, New Cairo',
            'phone' => '01000084547',
            'whatsapp' => '+201000084547',
            'google_maps_url' => 'https://maps.google.com/?q=Alef+Bookstore+Downtown+Mall+New+Cairo',
            'is_main_distributor' => 0,
            'display_order' => 5,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'الجيزة',
            'city_en' => 'Giza',
            'name_ar' => 'دار المعارف',
            'name_en' => 'Dar Al-Maaref',
            'branch_name_ar' => 'فرع الدقي',
            'branch_name_en' => 'Dokki Branch',
            'address_ar' => 'شارع التحرير، ميدان الدقي، الجيزة',
            'address_en' => 'Tahrir St, Dokki Square, Giza',
            'phone' => '02-37482315',
            'whatsapp' => '+201000600800',
            'google_maps_url' => 'https://maps.google.com/?q=Dar+Al+Maaref+Dokki+Giza',
            'is_main_distributor' => 1,
            'display_order' => 6,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'الجيزة',
            'city_en' => 'Giza',
            'name_ar' => 'مكتبة ديوان',
            'name_en' => 'Diwan Bookstore',
            'branch_name_ar' => 'فرع الشيخ زايد',
            'branch_name_en' => 'Sheikh Zayed Branch',
            'address_ar' => 'أركان بلازا، مدخل زايد 2000، الشيخ زايد، 6 أكتوبر',
            'address_en' => 'Arkan Plaza, Zayed 2000 Entrance, Sheikh Zayed',
            'phone' => '02-38500200',
            'whatsapp' => '+201222407084',
            'google_maps_url' => 'https://maps.google.com/?q=Diwan+Bookstore+Arkan+Plaza+Zayed',
            'is_main_distributor' => 0,
            'display_order' => 7,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'الإسكندرية',
            'city_en' => 'Alexandria',
            'name_ar' => 'دار المعارف',
            'name_en' => 'Dar Al-Maaref',
            'branch_name_ar' => 'فرع محطة الرمل',
            'branch_name_en' => 'Mahatet El-Raml Branch',
            'address_ar' => 'ميدان سعد زغلول، محطة الرمل، الإسكندرية',
            'address_en' => 'Saad Zaghloul Square, Mahatet El-Raml, Alexandria',
            'phone' => '03-4871234',
            'whatsapp' => '+201000600800',
            'google_maps_url' => 'https://maps.google.com/?q=Dar+Al+Maaref+Mahatet+El+Raml+Alexandria',
            'is_main_distributor' => 1,
            'display_order' => 8,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'الإسكندرية',
            'city_en' => 'Alexandria',
            'name_ar' => 'مكتبات الشروق',
            'name_en' => 'Shorouk Bookshop',
            'branch_name_ar' => 'فرع سيدي جابر',
            'branch_name_en' => 'Sidi Gaber Branch',
            'address_ar' => 'جرين بلازا مول، سموحة، سيدي جابر، الإسكندرية',
            'address_en' => 'Green Plaza Mall, Smouha, Alexandria',
            'phone' => '03-4209800',
            'whatsapp' => '+201000600700',
            'google_maps_url' => 'https://maps.google.com/?q=Shorouk+Bookshop+Green+Plaza+Alexandria',
            'is_main_distributor' => 0,
            'display_order' => 9,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'الدقهلية',
            'city_en' => 'Dakahlia',
            'name_ar' => 'مكتبة دار الكتاب',
            'name_en' => 'Dar Al-Kitab Bookshop',
            'branch_name_ar' => 'فرع المنصورة',
            'branch_name_en' => 'Mansoura Branch',
            'address_ar' => 'شارع الجمهورية، أمام بوابة جامعة المنصورة الرئيسية، المنصورة',
            'address_en' => 'El-Gomhouria St, in front of Mansoura University Main Gate',
            'phone' => '050-2234567',
            'whatsapp' => '+201012345678',
            'google_maps_url' => 'https://maps.google.com/?q=Mansoura+University+Gomhouria+Street',
            'is_main_distributor' => 1,
            'display_order' => 10,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'الغربية',
            'city_en' => 'Gharbia',
            'name_ar' => 'مكتبة الفكر العربي',
            'name_en' => 'Arab Thought Bookshop',
            'branch_name_ar' => 'فرع طنطا',
            'branch_name_en' => 'Tanta Branch',
            'address_ar' => 'شارع البحر (الجيش)، بجوار سينما ريفولي، طنطا',
            'address_en' => 'El-Bahr St, next to Rivoli Cinema, Tanta',
            'phone' => '040-3345678',
            'whatsapp' => '+201012345679',
            'google_maps_url' => 'https://maps.google.com/?q=El+Bahr+Street+Tanta',
            'is_main_distributor' => 0,
            'display_order' => 11,
        ],
        [
            'country_type' => 'egypt',
            'country_ar' => 'مصر',
            'country_en' => 'Egypt',
            'city_ar' => 'أسيوط',
            'city_en' => 'Assiut',
            'name_ar' => 'مكتبة النور',
            'name_en' => 'Al-Noor Bookstore',
            'branch_name_ar' => 'فرع أسيوط الرئيسي',
            'branch_name_en' => 'Main Assiut Branch',
            'address_ar' => 'شارع الجمهورية، أمام ديوان عام المحافظة، أسيوط',
            'address_en' => 'El-Gomhouria St, opposite Governorate Building, Assiut',
            'phone' => '088-2345678',
            'whatsapp' => '+201012345680',
            'google_maps_url' => 'https://maps.google.com/?q=Gomhouria+Street+Assiut',
            'is_main_distributor' => 1,
            'display_order' => 12,
        ],

        // --- خارج مصر (International) ---
        [
            'country_type' => 'international',
            'country_ar' => 'المملكة العربية السعودية',
            'country_en' => 'Saudi Arabia',
            'city_ar' => 'الرياض',
            'city_en' => 'Riyadh',
            'name_ar' => 'مكتبة جرير',
            'name_en' => 'Jarir Bookstore',
            'branch_name_ar' => 'فرع العليا العام',
            'branch_name_en' => 'Olaya Main Branch',
            'address_ar' => 'طريق العليا العام، حي الورود، الرياض',
            'address_en' => 'Olaya Main Road, Al-Worood, Riyadh',
            'phone' => '+966920000082',
            'whatsapp' => '+966920000082',
            'google_maps_url' => 'https://maps.google.com/?q=Jarir+Bookstore+Olaya+Riyadh',
            'is_main_distributor' => 1,
            'display_order' => 20,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'المملكة العربية السعودية',
            'country_en' => 'Saudi Arabia',
            'city_ar' => 'جدة',
            'city_en' => 'Jeddah',
            'name_ar' => 'مكتبة جرير',
            'name_en' => 'Jarir Bookstore',
            'branch_name_ar' => 'فرع طريق الأمير سلطان',
            'branch_name_en' => 'Prince Sultan Rd Branch',
            'address_ar' => 'طريق الأمير سلطان، حي الروضة، جدة',
            'address_en' => 'Prince Sultan Road, Al Rawdah, Jeddah',
            'phone' => '+966920000082',
            'whatsapp' => '+966920000082',
            'google_maps_url' => 'https://maps.google.com/?q=Jarir+Bookstore+Prince+Sultan+Jeddah',
            'is_main_distributor' => 1,
            'display_order' => 21,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'الإمارات العربية المتحدة',
            'country_en' => 'United Arab Emirates',
            'city_ar' => 'دبي',
            'city_en' => 'Dubai',
            'name_ar' => 'مكتبة كينوكونيا Kinokuniya',
            'name_en' => 'Kinokuniya Bookstore',
            'branch_name_ar' => 'فرع دبي مول',
            'branch_name_en' => 'The Dubai Mall Branch',
            'address_ar' => 'دبي مول، الطابق الثاني، قرب حلبة التزلج، دبي',
            'address_en' => 'The Dubai Mall, Level 2, Near Ice Rink, Dubai',
            'phone' => '+97144340111',
            'whatsapp' => '+97144340111',
            'google_maps_url' => 'https://maps.google.com/?q=Kinokuniya+Bookstore+Dubai+Mall',
            'is_main_distributor' => 1,
            'display_order' => 22,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'الإمارات العربية المتحدة',
            'country_en' => 'United Arab Emirates',
            'city_ar' => 'الشارقة',
            'city_en' => 'Sharjah',
            'name_ar' => 'مكتبات المجرودي Magrudy\'s',
            'name_en' => 'Magrudy\'s Bookshop',
            'branch_name_ar' => 'فرع المدينة الجامعية',
            'branch_name_en' => 'University City Branch',
            'address_ar' => 'المدينة الجامعية، الشارقة',
            'address_en' => 'University City, Sharjah',
            'phone' => '+97165050555',
            'whatsapp' => '+97165050555',
            'google_maps_url' => 'https://maps.google.com/?q=University+City+Sharjah',
            'is_main_distributor' => 0,
            'display_order' => 23,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'دولة الكويت',
            'country_en' => 'Kuwait',
            'city_ar' => 'الكويت',
            'city_en' => 'Kuwait City',
            'name_ar' => 'مكتبة آفاق للنشر والتوزيع',
            'name_en' => 'Afaq Bookstore',
            'branch_name_ar' => 'فرع السالمية',
            'branch_name_en' => 'Salmiya Branch',
            'address_ar' => 'شارع سالم المبارك، مجمع أوتاد، السالمية، الكويت',
            'address_en' => 'Salem Al Mubarak St, Owtad Mall, Salmiya, Kuwait',
            'phone' => '+96522256141',
            'whatsapp' => '+96599123456',
            'google_maps_url' => 'https://maps.google.com/?q=Afaq+Bookstore+Salmiya+Kuwait',
            'is_main_distributor' => 1,
            'display_order' => 24,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'المملكة الأردنية الهاشمية',
            'country_en' => 'Jordan',
            'city_ar' => 'عمّان',
            'city_en' => 'Amman',
            'name_ar' => 'دار الشروق للنشر والتوزيع',
            'name_en' => 'Dar Al-Shorouk Jordan',
            'branch_name_ar' => 'فرع الجاردنز',
            'branch_name_en' => 'Gardens Branch',
            'address_ar' => 'شارع وصفي التل (الجاردنز)، عمّان، الأردن',
            'address_en' => 'Wasfi Al-Tal St (Gardens), Amman, Jordan',
            'phone' => '+96265698710',
            'whatsapp' => '+962791234567',
            'google_maps_url' => 'https://maps.google.com/?q=Wasfi+Al-Tal+Street+Amman',
            'is_main_distributor' => 1,
            'display_order' => 25,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'جمهورية العراق',
            'country_en' => 'Iraq',
            'city_ar' => 'بغداد',
            'city_en' => 'Baghdad',
            'name_ar' => 'مكتبة دار السطور',
            'name_en' => 'Dar Al-Sutoor Bookshop',
            'branch_name_ar' => 'فرع شارع المتنبي',
            'branch_name_en' => 'Al-Mutanabbi St Branch',
            'address_ar' => 'شارع المتنبي الشهير، قرب مبنى القشلة، بغداد، العراق',
            'address_en' => 'Al-Mutanabbi Street, near Qishla, Baghdad, Iraq',
            'phone' => '+9647701234567',
            'whatsapp' => '+9647701234567',
            'google_maps_url' => 'https://maps.google.com/?q=Al-Mutanabbi+Street+Baghdad',
            'is_main_distributor' => 1,
            'display_order' => 26,
        ],
        [
            'country_type' => 'international',
            'country_ar' => 'معارض الكتاب الدولية',
            'country_en' => 'International Book Fairs',
            'city_ar' => 'كافة العواصم',
            'city_en' => 'All Capitals',
            'name_ar' => 'جناح دار نشر مدينة الأدباء',
            'name_en' => 'Madinat Al-Odabaa Pavilion',
            'branch_name_ar' => 'المعارض الدولية السنوية',
            'branch_name_en' => 'Annual International Fairs',
            'address_ar' => 'معارض الكتاب الدولية (الرياض، الشارقة، أبوظبي، القاهرة، مسقط، الدوحة، والدار البيضاء)',
            'address_en' => 'International Book Fairs (Riyadh, Sharjah, Abu Dhabi, Cairo, Muscat, Doha, Casablanca)',
            'phone' => '02-339-650-60',
            'whatsapp' => '+201000000000',
            'google_maps_url' => 'https://maps.google.com/?q=Cairo+International+Book+Fair',
            'is_main_distributor' => 1,
            'display_order' => 27,
        ],
    ];

    $ins = $pdo->prepare("
        INSERT INTO `points_of_sale` (
            id, country_type, country_ar, country_en, city_ar, city_en,
            name_ar, name_en, branch_name_ar, branch_name_en, address_ar, address_en,
            phone, whatsapp, google_maps_url, is_main_distributor, is_active, display_order
        ) VALUES (
            :id, :country_type, :country_ar, :country_en, :city_ar, :city_en,
            :name_ar, :name_en, :branch_name_ar, :branch_name_en, :address_ar, :address_en,
            :phone, :whatsapp, :google_maps_url, :is_main_distributor, 1, :display_order
        )
    ");

    $count = 0;
    foreach ($branches as $b) {
        $id = Database::uuid();
        $params = array_merge(['id' => $id], $b);
        $ins->execute($params);
        $count++;
    }

    $totalEgypt = (int) $pdo->query("SELECT COUNT(*) FROM points_of_sale WHERE country_type = 'egypt' AND is_active = 1")->fetchColumn();
    $totalIntl = (int) $pdo->query("SELECT COUNT(*) FROM points_of_sale WHERE country_type = 'international' AND is_active = 1")->fetchColumn();

    Response::ok([
        'message' => 'Points of sale initialized successfully!',
        'total_inserted' => $count,
        'egypt_branches' => $totalEgypt,
        'international_branches' => $totalIntl,
    ]);
} catch (\Throwable $e) {
    Response::serverError($e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine());
}
